---
version: '3.8'

services:
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    # network_mode: host
    ports:
      - 9090:9090
    user: "1000:1000"
    restart: unless-stopped
    command:
      - --config.file=/PROMETHEUS_CONFIG_FILE.yml
    volumes:
      - ./prometheus.yml:/PROMETHEUS_CONFIG_FILE.yml  # 配置文件
      - ./prometheus_data:/opt/bitnami/prometheus/data # 数据存储目录
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    # network_mode: host
    ports:
      - 3000:3000
    user: "1000:1000"
    restart: unless-stopped
    volumes:
      - ./grafana_data:/var/lib/grafana

  httpproxy:
    image: httpproxy
    container_name: httpproxy
    # network_mode: host
    ports:
      - 8079:8079
      - 8080:8080
    restart: unless-stopped

  traffic-detector:
    image: traffic-detector
    container_name: traffic-detector
    # network_mode: host
    ports:
      - 8000:8000
    restart: unless-stopped

  httpserver:
    image: httpserver
    container_name: httpserver
    # network_mode: host
    ports:
      - 8000:8000
    restart: unless-stopped